# Generated by Django 4.1.3 on 2022-11-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='Menu.seller', verbose_name='Sellers'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carcategories', to='Menu.car', verbose_name='Car'),
        ),
    ]
