# Generated by Django 4.1.4 on 2022-12-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_clientcontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'verbose_name': 'ClientContact', 'verbose_name_plural': 'ClientContacts'},
        ),
    ]
